# Dependencies
categories: "distributed-systems|consensus-protocols|finance|math|physics|machine-learning|programming|"

# Permalinks
permalink:        /:year/:month/:day/:title/

theme: hyde
title: CarpeRisus 
tagline: 'Seizing joy from thought'
description: Welcome to JD's digital life existence! This is a place for me to post projects and thoughts. 

author:
  name:           'JD'
  email:        'We will think about this.'
  

version:          1.0.0

github:
  repo:           https://github.com/jdgithub2389/

